name: RPM build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-armv7hl:
    runs-on: ubuntu-latest
    name: Build armv7hl
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build armv7hl RPMS
      uses: R1tschY/sailfish-sdk-action@v1
      with:
        arch: 'armv7hl'
        release: '3.4.0.24'
        fix-version: false
        enable-debug: true
        #check: true

    - name: Upload RPMS
      uses: actions/upload-artifact@v2
      with:
        name: harbour-determinant-armv7hl
        path: RPMS

  build-i486:
    runs-on: ubuntu-latest
    name: Build i486
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build i486 RPMS
      uses: R1tschY/sailfish-sdk-action@v1
      with:
        arch: 'i486'
        release: '3.4.0.24'
        fix-version: false
        enable-debug: true
        #check: true

    - name: Upload RPMS
      uses: actions/upload-artifact@v2
      with:
        name: harbour-determinant-i486
        path: RPMS

  build-aarch64:
    runs-on: ubuntu-latest
    name: Build aarch64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build aarch64 RPMS
      uses: R1tschY/sailfish-sdk-action@v1
      with:
        arch: 'aarch64'
        release: '3.4.0.24'
        fix-version: false
        enable-debug: true
        #check: true

    - name: Upload RPMS
      uses: actions/upload-artifact@v2
      with:
        name: harbour-determinant-aarch64
        path: RPMS