name: RPM build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build armv7hl RPMS
      uses: R1tschY/sailfish-sdk-action@v1
      with:
        arch: 'armv7hl'
        release: '3.3.0.16'
        fix-version: false
        enable-debug: true
        #check: true

    - name: Clean 
      run: git clean -q -d -f -x -e RPMS

    - name: Build i486 RPMS
      uses: R1tschY/sailfish-sdk-action@v1
      with:
        arch: 'i486'
        release: '3.3.0.16'
        fix-version: false
        enable-debug: true
        #check: true

    - name: Upload RPMS
      uses: actions/upload-artifact@v2
      with:
        name: rpms
        path: RPMS